// import { ICargo } from "@/features/log/active/ui/CargoCard";
// import { Cargo } from "@/features/log/screen/components/CargoCard";

// export const cargoData: ICargo[] = [
//   {
//     id: 1857878791,
//     manager: "Бойко В.М.",
//     from: "Смолигів, Волинська обл.",
//     to: "Турку, Фінляндія",
//     details: "ВІЛЬНИЙ ДОСТУП! 2 авто, крита",
//     status: "active",
//     time: "4 години тому",
//     company: "Nestrade",
//     vehiclesNeeded: 2,
//     type: "Крита",
//     messages: 0,
//   },
//   {
//     id: 1854087872,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
//   {
//     id: 1854087873,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
//   {
//     id: 1854087874,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
//   {
//     id: 1854087875,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
//   {
//     id: 1854076766,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
//   {
//     id: 1854054547,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
//   {
//     id: 1854012300,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
//   {
//     id: 1854032131123,
//     manager: "Шиліна С.Б.",
//     from: "Клайпеда, Литва",
//     to: "Київ, Україна",
//     details: "Сировина для виготовлення PET-пляшок",
//     status: "active",
//     time: "4 години тому",
//     company: "Інпласт Україна",
//     vehiclesNeeded: 4,
//     type: "Тент",
//     messages: 0,
//   },
// ];