import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../shared/styles/globals.css";
import { MainProvider } from "@/shared/providers";
import NextTopLoader from "nextjs-toploader";
import { getProfile } from "@/shared/server/getProfile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    absolute: "ІСТендер платформа",
    template: "%s | ІСТендер",
  },
  description: "Generated by create next app",

  icons: {
    icon: [
      {
        url: "/icons/favicon.ico",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/icons/favicon.ico",
        media: "(prefers-color-scheme: dark)",
      },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png" }],
  },
};
// test

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await getProfile();
  console.log(profile, "profile");

  return (
    <html lang="en" suppressHydrationWarning className="scrollbar-thin">
      <body
        // wotdisconnected="true"
        className={`${geistSans.variable} ${geistMono.variable} antialiased scrollbar-thin `}
      >
        <NextTopLoader
          showSpinner={false} // вимикаємо спінер
          crawl={true} // смужка буде плавно рухатись при завантаженні
          crawlSpeed={200} // швидкість "просування" смужки
          showAtBottom={false} // зверху сторінки
          color="#14b8a6" // сучасний колір (teal/акцент)
          height={3} // тонка смужка, не відволікає
          initialPosition={0.08} // початкова позиція на 8%
          easing="ease" // плавна анімація
          speed={300} // швидкість анімації завершення
          shadow="0 0 8px #14b8a6,0 0 4px #14b8a6" // легка тінь для видимості
          zIndex={2000} // поверх всіх елементів
          showForHashAnchor={true} // якщо переходиш на хеш-лінк, теж показує
        />

        <MainProvider profile={profile!!}>{children}</MainProvider>
      </body>
    </html>
  );
}
