# name: Deploy Next.js

# on:
#   push:
#     branches: [main]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20
#       - run: npm install
#         working-directory: ./frontend
#       - run: npm run build
#         working-directory: ./frontend
#       - name: Build Docker
#         run: docker build -t my-next ./frontend
#       - name: Push Docker
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - run: docker push mydockerhubuser/my-next:latest
#       - name: Deploy on server
#         uses: appleboy/ssh-action@v0.1.9
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             docker pull mydockerhubuser/my-next:latest
#             docker stop next || true
#             docker rm next || true
#             docker run -d --name next -p 3000:3000 mydockerhubuser/my-next:latest
name: Deploy Next.js

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
  with:
    host: ${{ secrets.SERVER_IP }}
    username: ${{ secrets.SERVER_USER }}
    password: ${{ secrets.SERVER_PASSWORD }}
    script: |
      cd /dragantataryn/ict/tender-client
      git pull origin main
      npm install --production
      npm run build
      pm2 restart next || pm2 start npm --name next -- start
